version: "3"

services:
  webapp:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
#       - SIGNUPS_ALLOWED=false
    ports:
      - "82:80"
      - "3012:3012"
    volumes:
      - ./data:/data
